### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ahrlad** [specadmin/RTD2660AVR#4]
I've been studying this code for a bit, since I've been trying to hack the 2660 for a while. I've seen that it's released as open source, but not under which specific license? I'd be grateful to know, so I don't mess stuff up.

**Comment by specadmin** [comment]
Hello, ahrlad. I'm not good at licensing. Could you please advise me on a proper license? My goal is to gather developers in order to hack 2660 completely and to create a ready-to-use and cheap tool for making LCD interfaces. This code, as a result of our work, is absolutely free: everyone can use it. However, it comes "as is", with no guarantees and no responsibilities.

**Comment by ahrlad** [comment]
Thank you for answering!

Open source licensing is meant to make things simple, the entire point of
it is making sure lawyers aren't required. But making licensing terms
explicit makes it much simpler for people to use it in other projects,
without having to worry that they're doing things they shouldn't. Having a
"LICENSE.md" file in the root of the repo really clears that stuff up.

I would recommend just choosing the GPL3 license in any repo containing
code that you want to contribute to the open source scene, since it's
popular and well-understood. Github makes this extremely simple! In the web
interface, you can create a new file called "LICENSE.md" (case sensitive)
in the root of a repository, choose a license from their list, and you
won't get this question again ;)

If licensing terms interest you, I'll try to explain the little I know
about them in this mail, and you can read github's excellent explanation
here:
https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository

All of these licenses will contain disclaimers about liabilities and no
warranties offered and such. The only really important choice, if you want
people to use your code freely, is whether you want to make the code
available under a permissive license or a copyleft license, since that
affects which projects the code can be used in.

A permissive license means that other people can use your code with the
only requirement being that acknowledge they're using it. If they make a
product with it, they're not required to release their source code in turn
- like when Sony uses open source code in their Playstations, they only use
"permissive" stuff so they don't have to release the firmware source code.
It can also be used in open-source projects with other license terms,
without affecting those projects' licensing. A very common permissive
license is the MIT license, shown here:
*https://github.com/licenses/license-templates/blob/master/templates/mit.txt
<https://github.com/licenses/license-templates/blob/master/templates/mit.txt>*

A copyleft license means that if someone uses the code to make a product of
some sort, the code must be made available to people using that product.
It's more like the firmware in Android phones - companies can't use the
Linux components without releasing the source code. The most common
copyleft license is of course the GPL:
*https://github.com/licenses/license-templates/blob/master/templates/gpl3.txt
<https://github.com/licenses/license-templates/blob/master/templates/gpl3.txt>*

The terms are much more complicated in that license, but people are very
familiar with it. The basic point of it is to make sure that the open
source  software stays open - so it can be use in an Android phone
firmware, but not in a closed-source Playstation firmware.

If you want my advice, I'd recommend the GPL - the limitations on use in
the GPL only really bothers companies that make commercial products, it
doesn't stop anyone from playing around with the code or using it in their
own projects. Also, projects using copyleft licenses have a somewhat easier
time attracting developers, since they can contribute and know their work
won't be made private by someone else.

Anyway I hope I haven't wasted too much of your time - I'm not good at
explaining this stuff, if it sounds like I'm "dumbing things down", I'm
why. Thanks for your time, and thanks again for answering!

/Harald

**Comment by specadmin** [comment]
Hey Harald!

Thanks for your explanations! I have added the license regarding your recommendation.

**Comment by ahrlad** [comment]
That's awesome! Thank you.
